import type { ProductListing } from "@/types/product";
import { DEFAULT_VALUES } from "@/config/default-values";
import { STORE_BRANDING_DEFAULTS } from "@/config/store-branding";
import { buildHiglouDescriptionHtml } from "@/lib/ebay/description-html";
import { nanoid } from "nanoid";

export function createEmptyListing(): ProductListing {
  const now = new Date().toISOString();
  return {
    id: nanoid(),
    status: "Uploaded",
    title: "",
    subtitle: "",
    brand: "",
    collection: "",
    model: "",
    mpn: "",
    upc: "",
    sku: "",
    productType: "",
    categoryId: "",
    categoryName: "",
    condition: "New",
    conditionId: "NEW",
    conditionDescription: "",
    price: null,
    quantity: DEFAULT_VALUES.quantity,
    listingFormat: DEFAULT_VALUES.listingFormat,
    bestOffer: false,
    minimumOffer: null,
    autoAcceptOffer: null,
    size: "",
    type: "",
    colors: [],
    materials: [],
    pattern: "",
    style: "",
    department: "",
    room: "",
    features: [],
    setIncludes: [],
    missingItems: [],
    numberOfItems: null,
    careInstructions: [],
    countryOfManufacture: "",
    descriptionSummary: "",
    descriptionHtml: "",
    itemSpecifics: [],
    images: [],
    shippingPolicyId: "",
    returnPolicyId: "",
    paymentPolicyId: "",
    handlingTime: DEFAULT_VALUES.handlingTime,
    itemLocation: DEFAULT_VALUES.itemLocation,
    postalCode: DEFAULT_VALUES.postalCode,
    country: DEFAULT_VALUES.country,
    freeShipping: false,
    shippingCost: null,
    shippingService: "",
    createdAt: now,
    updatedAt: now,
  };
}

export function createDemoListing(): ProductListing {
  const now = new Date().toISOString();
  const title =
    "Chic Home Clayton Queen 10 Piece Comforter Set Yellow Gray White";
  const features = [
    "10-piece bedding comforter set",
    "Queen size",
    "Yellow, gray, and white color palette",
  ];
  const setIncludes = [
    "1 Comforter",
    "2 Shams",
    "Decorative pillows",
    "See photos for complete package details",
  ];

  return {
    id: nanoid(),
    status: "Needs Review",
    title,
    subtitle: "Bedding comforter set",
    brand: "Chic Home",
    collection: "Clayton",
    model: "CS164S",
    mpn: "CS164S",
    upc: "",
    sku: "CH-CLAYTON-CS164S-QN-YLW",
    productType: "Comforter Set",
    categoryId: "177019",
    categoryName: "Comforter Sets",
    condition: "New",
    conditionId: "NEW",
    conditionDescription: "New in original packaging. See photos for details.",
    price: 49.99,
    quantity: DEFAULT_VALUES.quantity,
    listingFormat: DEFAULT_VALUES.listingFormat,
    bestOffer: false,
    minimumOffer: null,
    autoAcceptOffer: null,
    size: "Queen",
    type: "Comforter Set",
    colors: ["Yellow", "Gray", "White"],
    materials: [],
    pattern: "",
    style: "",
    department: "",
    room: "Bedroom",
    features,
    setIncludes,
    missingItems: [],
    numberOfItems: 10,
    careInstructions: [],
    countryOfManufacture: "",
    descriptionSummary:
      "Chic Home Clayton Queen comforter set featuring a yellow, gray, and white design. Review photos for exact package contents.",
    descriptionHtml: buildHiglouDescriptionHtml({
      productTitle: title,
      productIntroduction:
        "Chic Home Clayton Queen comforter set featuring a yellow, gray, and white design. Review photos for exact package contents.",
      features,
      itemCondition: "New — New in original packaging. See photos for details.",
      packageContents: setIncludes,
      shippingInformation: STORE_BRANDING_DEFAULTS.shippingInformation,
      specs: [
        { label: "Brand", value: "Chic Home" },
        { label: "Size", value: "Queen" },
        { label: "Color", value: "Yellow / Gray / White" },
        { label: "Type", value: "Comforter Set" },
        { label: "Model", value: "CS164S" },
      ],
    }),
    itemSpecifics: [
      { key: "C:Brand", label: "Brand", value: "Chic Home", required: true, confidence: 0.9 },
      { key: "C:Size", label: "Size", value: "Queen", required: true, confidence: 0.85 },
      { key: "C:Type", label: "Type", value: "Comforter Set", required: true, confidence: 0.8 },
      {
        key: "C:Color",
        label: "Color",
        value: "Yellow|Gray|White",
        required: true,
        confidence: 0.8,
      },
      {
        key: "C:Number of Items in Set",
        label: "Number of Items in Set",
        value: "10",
        confidence: 0.75,
      },
      { key: "C:Model", label: "Model", value: "CS164S", confidence: 0.7 },
      { key: "C:MPN", label: "MPN", value: "CS164S", confidence: 0.7 },
      { key: "C:Room", label: "Room", value: "Bedroom", confidence: 0.6 },
    ],
    images: [
      {
        id: nanoid(),
        url: "https://ir.ebaystatic.com/cr/v/c1/rsc/ebay_logo_512.png",
        fileName: "primary.png",
        sortOrder: 0,
        isPrimary: true,
        mimeType: "image/png",
        sizeBytes: 0,
        uploadProgress: 100,
      },
      {
        id: nanoid(),
        url: "https://i.ebayimg.com/images/g/sample/s-l1600.jpg",
        fileName: "secondary.jpg",
        sortOrder: 1,
        isPrimary: false,
        mimeType: "image/jpeg",
        sizeBytes: 0,
        uploadProgress: 100,
      },
    ],
    shippingPolicyId: "",
    returnPolicyId: "",
    paymentPolicyId: "",
    handlingTime: DEFAULT_VALUES.handlingTime,
    itemLocation: DEFAULT_VALUES.itemLocation,
    postalCode: DEFAULT_VALUES.postalCode,
    country: DEFAULT_VALUES.country,
    freeShipping: false,
    shippingCost: null,
    shippingService: "",
    createdAt: now,
    updatedAt: now,
  };
}
